### ISSUE TITLE
do we need to open port 5280

### ISSUE THREAD

**Issue by pratik9722** [christiancuri/Docs#10]
Although it's working fine but I'm curious to know do we need to open port 5280 ?
 # BOSH
    location /http-bind {
        proxy_pass      http://localhost:5280/http-bind;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $http_host;
    }

**Comment by christiancuri** [comment]
Not is necessary, because nginx handle traffic by proxy to service http-bind

**Comment by pratik9722** [comment]
Gotcha! thank you for the script.
