### ISSUE TITLE
jicofo err

### ISSUE THREAD

**Issue by salehy1981** [christiancuri/Docs#2]
hi there ,your guide look solid. but upon create room any one as guest or even with token join meeting it will destroy and showing message unfortunetly some thing going wrong. i made fresh install on ubuntu 18.04. below is jicofo and prosody log for failure. 

`May 02 17:29:33 conference.meet.example.com:muc_domain_mapper	warn	Session filters applied
May 02 17:29:33 mod_bosh	info	New BOSH session, assigned it sid '1eb7fe88-9985-4309-80a0-945aafffd937'
May 02 17:29:33 bosh1eb7fe88-9985-4309-80a0-945aafffd937	info	Authenticated as c0c74226-9d39-41c6-8b1f-e2fb25a742ad@meet.example.com
May 02 17:30:33 conference.meet.example.com:muc_domain_mapper	warn	Session filters applied
May 02 17:30:33 mod_bosh	info	New BOSH session, assigned it sid '8e43a6f2-7c65-47ce-af5c-e741208e49ab'
May 02 17:30:33 bosh8e43a6f2-7c65-47ce-af5c-e741208e49ab	info	Authenticated as b0dd7477-e691-497e-83a9-4ab7ad63e550@guest.meet.example.com
May 02 17:30:35 bosh1eb7fe88-9985-4309-80a0-945aafffd937	info	BOSH client disconnected: session close
May 02 17:30:35 speakerstats.meet.example.com:speakerstats_component	warn	A module has been configured that triggers external events.
May 02 17:30:35 speakerstats.meet.example.com:speakerstats_component	warn	Implement this lib to trigger external events.
May 02 17:30:35 bosh8e43a6f2-7c65-47ce-af5c-e741208e49ab	info	BOSH client disconnected: session close

Jicofo 2020-05-02 17:38:56.819 INFO: [57] org.jitsi.jicofo.FocusManager.log() Created new focus for mmm@conference.meet.example.com@auth.meet.example.com. Conference count 1,options: 
Jicofo 2020-05-02 17:38:56.819 INFO: [57] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Joining the room: mmm@conference.meet.example.com
Jicofo 2020-05-02 17:38:57.325 INFO: [84] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@7eb22cbf member=ChatMember[mmm@conference.meet.example.com/0dd06633, jid: null]@1886768409]
Jicofo 2020-05-02 17:38:57.331 INFO: [84] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member mmm@conference.meet.example.com/0dd06633 joined.
Jicofo 2020-05-02 17:39:32.692 INFO: [71] org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq().401 Focus request for room: mmm@conference.meet.example.com
Jicofo 2020-05-02 17:39:32.778 INFO: [88] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@7eb22cbf member=ChatMember[mmm@conference.meet.example.com/bc224384, jid: null]@1826148452]
Jicofo 2020-05-02 17:39:32.778 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member mmm@conference.meet.example.com/bc224384 joined.
Jicofo 2020-05-02 17:39:32.780 WARNING: [88] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-02 17:39:32.781 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-05-02 17:39:32.787 WARNING: [88] org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-02 17:39:32.790 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
Jicofo 2020-05-02 17:39:33.345 INFO: [88] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@7eb22cbf member=ChatMember[mmm@conference.meet.example.com/bc224384, jid: bc224384-7778-4c46-90f4-11678a8fb19e@guest.meet.example.com/V4VV4GLy]@1826148452]
Jicofo 2020-05-02 17:39:33.346 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member mmm@conference.meet.example.com/bc224384 is leaving
Jicofo 2020-05-02 17:39:33.347 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, mmm@conference.meet.example.com/bc224384
Jicofo 2020-05-02 17:39:35.391 INFO: [88] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberLeft sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@7eb22cbf member=ChatMember[mmm@conference.meet.example.com/0dd06633, jid: 0dd06633-9ae5-4dac-bc69-0318a29b2048@meet.example.com/O8iLTHw7]@1886768409]
Jicofo 2020-05-02 17:39:35.391 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member mmm@conference.meet.example.com/0dd06633 is leaving
Jicofo 2020-05-02 17:39:35.392 INFO: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Removed participant: true, mmm@conference.meet.example.com/0dd06633
Jicofo 2020-05-02 17:39:35.402 INFO: [88] org.jitsi.jicofo.FocusManager.log() Disposed conference for room: mmm@conference.meet.example.com conference count: 0

`

**Comment by christiancuri** [comment]
Hi, you have changed Bridge in your JVB ?

`
org.jitsi.jicofo.bridge.BridgeSelectionStrategy.log() Failed to select initial bridge for participantRegion=null
Jicofo 2020-05-02 17:39:32.790 SEVERE: [88] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Can not invite participant -- no bridge available.
`

this message is from octo, using bridge selection to select for which the bridge send the participant
