### ISSUE TITLE
Error with Luacrypto

### ISSUE THREAD

**Issue by altiport** [christiancuri/Docs#3]
I get the following error in Ubuntu 18.04 .

> Installing https://luarocks.org/luacrypto-0.3.2-2.src.rock
> gcc -O2 -fPIC -I/usr/include/lua5.2 -c src/lcrypto.c -o src/lcrypto.o -I/usr/include
> sh: 1: gcc: not found
> Error: Build error: Failed compiling object src/lcrypto.o

**Comment by christiancuri** [comment]
Try install gcc, is strange, because ubuntu already have gcc, but, try install using

Join in sudo user
`sudo su`

After join, run the following command

`apt-get install gcc -y`

**Comment by christiancuri** [comment]
To prevent this error, i will go update the doc installing the necessary dependencies like gcc and unzip

**Comment by christiancuri** [comment]
I just updated the doc to prevent this error.

**Comment by MobtgZhang** [comment]
The problem happened as in my computer,the operating is ubuntu19.10, and I bagged to ask for advice
